name: Infraestructura + Restauraci贸n de Base de Datos en Azure

on:
  push:
    branches: [main]

jobs:
  deploy-lab3-infra-and-restore:
    runs-on: windows-latest

    steps:
    - name: Checkout del repositorio
      uses: actions/checkout@v3

    - name: Login a Azure
      uses: azure/login@v1
      with:
        creds: ${{ secrets.AZURE_CREDENTIALS }}

    - name: Setup Terraform
      uses: hashicorp/setup-terraform@v3
      with:
        terraform_version: 1.6.6

    - name: Crear archivo terraform.tfvars
      run: |
        echo "subscription_id = \"${{ secrets.SUBSCRIPTION_ID }}\"" > ./infra/terraform.tfvars
        echo "sqladmin_username = \"${{ secrets.SQL_USERNAME }}\"" >> ./infra/terraform.tfvars
        echo "sqladmin_password = \"${{ secrets.SQL_PASSWORD }}\"" >> ./infra/terraform.tfvars
        echo "resource_group_name = \"${{ secrets.RESOURCE_GROUP }}\"" >> ./infra/terraform.tfvars
        echo "location = \"${{ secrets.LOCATION }}\"" >> ./infra/terraform.tfvars

    - name: Terraform Init
      working-directory: ./infra
      run: terraform init

    - name: Terraform Plan
      working-directory: ./infra
      run: terraform plan -var-file="terraform.tfvars" -out="main.tfplan"

    - name: Terraform Apply
      working-directory: ./infra
      run: terraform apply -auto-approve "main.tfplan"

    - name: Instalar m贸dulo SqlServer para PowerShell
      run: |
        Install-Module -Name SqlServer -Force -SkipPublisherCheck -AllowClobber

    - name: Restaurar base de datos desde .bak
      shell: pwsh
      run: |
        $serverName = "${{ secrets.SQL_SERVER }}"
        $databaseName = "dbpowerbi"  # Nombre de la base de datos a restaurar
        $username = "${{ secrets.SQL_USERNAME }}"
        $password = "${{ secrets.SQL_PASSWORD }}"
        $bakFilePath = "AdventureWorksLT2016.bak"  # Ruta completa del archivo .bak en el servidor

        $connectionString = "Server=$serverName;Database=$databaseName;User Id=$username;Password=$password;"

        # Ejecutar la restauraci贸n desde el archivo .bak
        $restoreQuery = @"
        RESTORE DATABASE [$databaseName] 
        FROM DISK = N'$bakFilePath' 
        WITH REPLACE, RECOVERY;
        "@

        # Ejecutar el script de restauraci贸n
        Invoke-Sqlcmd -ConnectionString $connectionString -Query $restoreQuery
